version: 2.1

parameters:
  model_name:
    type: string
    default: "gpt2"
    description: "HuggingFace Model Path"
  
  dataset_name:
    type: string
    default: "karpathy/tiny_shakespeare"
  
orbs:
  python: circleci/python@3.0.0

jobs:
  train-and-version-lora:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip

      - run:
          name: Setup DVC with Secure Credentials
          command: |
            if [ ! -d ".dvc" ]; then
              dvc init
            else
              echo "DVC already initialized"
            fi
            dvc remote add -d storage gdrive://${GDRIVE_FOLDER_ID}
            if [ ! -z "${GDRIVE_CONFIG_B64}" ]; then
              # Create credentials from environment variable
              echo "${GDRIVE_CONFIG_B64}" | base64 --decode > /tmp/gdrive_credentials.json
              dvc remote modify storage gdrive_use_service_account true
              dvc remote modify storage gdrive_service_account_json_file_path /tmp/gdrive_credentials.json
            fi
      - run:
          name: Train LoRA Adapter
          command: |
            python train.py \
              --model_name << pipeline.parameters.model_name >> \
              --dataset_name << pipeline.parameters.dataset_name >> \

      - run:
          name: DVC Versioning with Secure Credentials
          command: |
            MODEL_NAME=$(echo << pipeline.parameters.model_name >> | tr '/' '-')
            OUTPUT_DIR="./results/latest_lora_adapter"
            dvc add ${OUTPUT_DIR}
            dvc push
            git add results/latest_lora_adapter.dvc
            git config --global user.email ${GIT_CONFIG_EMAIL}
            git config --global user.name ${GIT_CONFIG_USERNAME}
            git commit -m "Update LORA Adapter Post Training"
            git push -u ${GITHUB_REPO_URL} main

            if [ -f "/tmp/gdrive_credentials.json" ]; then
              rm /tmp/gdrive_credentials.json
            fi

workflows:
  train-workflow:
    jobs:
      - train-and-version-lora:
          name: << pipeline.parameters.model_name >>-<< pipeline.parameters.dataset_name >>
